 language: ruby
os: linux
arch: s390x

addons:
  postgresql: 9.6

rvm: 2.6.3

cache: bundler

jobs:
  include:
    - stage: "rspec"
      script: bundle exec rspec
      before_script:
        - "bundle exec rake db:create db:migrate"